FROM python:3.11.4-slim-buster

ENV APP_HOME=/app

WORKDIR $APP_HOME
ENV PYTHONPATH=$APP_HOME

COPY requirements.txt .
COPY requirements-dev.txt .

RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

COPY Scripts Scripts
RUN chmod +x Scripts/*.sh

CMD ["bash", "Scripts/entrypoint-dev-jupyter.sh"]