name: CI/CD Pipeline

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

env:
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USER }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.sha }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  PYTHON_VERSION: '3.x'
  LINTERS: 'ruff'
  LINTER_CMD: 'ruff check src'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ${{ env.LINTERS }}
    - name: Run linter
      run: ${{ env.LINTER_CMD }}

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout repository
      run: ls -la
    - name: Build Docker image
      run: docker build -f Dockerfile.prod -t ${{ env.IMAGE_NAME }} .
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USER }}
        password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push image to Docker Hub
      run: docker push ${{ env.IMAGE_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USER }}
        key: ${{ env.SERVER_SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ env.IMAGE_NAME }}
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true
          docker run -d -p 8890:8890 --name ${{ env.CONTAINER_NAME }} ${{ env.IMAGE_NAME }}